artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/moreshwarnabar/text-summarizer/raw/main/samsum_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/dataset

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.json", "test.json", "val.json"]

data_transformation:
  root_dir: artifacts/data_transformation
  dataset: samsum
  tokenizer_name: google/pegasus-cnn_dailymail
